name: DAST con OWASP ZAP en URL Pública

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  issues: write

jobs:
  owasp-zap-scan:
    name: Escaneo DAST Externo
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout del repositorio
        uses: actions/checkout@v7.0.1

      - name: Ejecutar OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'https://pentest-ground.com:4280'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        continue-on-error: true

      - name: Subir reporte de ZAP como artefacto
        uses: actions/upload-artifact@v7.0.1
        with:
          name: zap-scan-report
          path: |
            report.html
            report.md
